language: generic
branches:
  only:
    - master
cache:
  directories:
    - vendor
sudo: required
services:
  - docker
env:
  - DOCKER_BUILD_FLAGS="--pull --no-cache"
install:
  - make bootstrap
script:
  - make build test-cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
